# Generated by Django 5.2.17 on 2026-08-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, help_text='Role / title / relevance', max_length=255)),
                ('where_met', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['name'],
            },
        ),
    ]
