# Generated by Django 5.2.17 on 2026-08-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='daily', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField(blank=True, null=True)),
                ('what_did_i_learn', models.TextField(blank=True)),
                ('what_did_i_build', models.TextField(blank=True)),
                ('what_challenged_me', models.TextField(blank=True)),
                ('what_mistake_did_i_make', models.TextField(blank=True)),
                ('what_did_i_understand_better', models.TextField(blank=True)),
                ('what_am_i_grateful_for', models.TextField(blank=True)),
                ('what_should_i_improve', models.TextField(blank=True)),
                ('what_did_i_avoid', models.TextField(blank=True)),
                ('what_should_i_do_differently', models.TextField(blank=True)),
                ('free_write', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-period_start'],
            },
        ),
    ]
