# Generated by Django 5.2.17 on 2026-08-10 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('academy_type', models.CharField(choices=[('anchor', 'Anchor (continuous)'), ('rotating', 'Rotating (one at a time)')], default='rotating', max_length=10)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color used in the UI', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier used in the UI', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Currently in use vs. archived')),
                ('drive_folder_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'academies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('objective', models.TextField(help_text='Primary learning objective for this period')),
                ('expected_outcome', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True)),
                ('reflection_what_learned', models.TextField(blank=True)),
                ('reflection_what_improved', models.TextField(blank=True)),
                ('reflection_what_needs_work', models.TextField(blank=True)),
                ('reflection_continue_practicing', models.TextField(blank=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academies.academy')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
