# Generated by Django 5.2.17 on 2026-08-10 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academies', '0001_initial'),
        ('core', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('book', 'Book'), ('podcast', 'Podcast'), ('video', 'Video'), ('course', 'Course'), ('article', 'Article'), ('documentation', 'Documentation'), ('pdf', 'PDF'), ('website', 'Website')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('want_to_learn', 'Want to Learn'), ('currently_learning', 'Currently Learning'), ('completed', 'Completed'), ('applied', 'Applied'), ('reviewed', 'Reviewed'), ('mastered', 'Mastered')], default='discovered', max_length=20)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('key_lessons', models.TextField(blank=True)),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='academies.academy')),
                ('tags', models.ManyToManyField(blank=True, related_name='resources', to='core.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.CharField(blank=True, max_length=255)),
                ('speaker', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('date_listened', models.DateField(blank=True, null=True)),
                ('quotes', models.TextField(blank=True)),
                ('questions', models.TextField(blank=True)),
                ('reflection', models.TextField(blank=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_detail', to='resources.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('cover_url', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5', null=True)),
                ('key_ideas', models.TextField(blank=True)),
                ('quotes', models.TextField(blank=True)),
                ('reflections', models.TextField(blank=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_detail', to='resources.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=10)),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('synced_to_drive_at', models.DateTimeField(blank=True, null=True)),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='academies.academy')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notes.note')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='resources.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('date_watched', models.DateField(blank=True, null=True)),
                ('bookmarks', models.TextField(blank=True)),
                ('questions', models.TextField(blank=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_detail', to='resources.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
