# Generated by Django 5.2.17 on 2026-08-10 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academies', '0001_initial'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, help_text='Markdown supported')),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='academies.academy')),
                ('related_goals', models.ManyToManyField(blank=True, related_name='related_notes', to='goals.goal')),
                ('related_notes', models.ManyToManyField(blank=True, to='notes.note')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
