# Generated by Django 5.2.17 on 2026-08-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('notes', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='related_resources',
            field=models.ManyToManyField(blank=True, related_name='related_notes', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='core.tag'),
        ),
    ]
